#!/usr/bin/env python3
"""Generate blockMeshDict for the NASA wall-mounted hump (CFDVAL2004 baseline).

Geometry (chord c = 1 m for unit reference):
  - channel x in [-2.14, 4.0], y in [0, 0.91], unit z-thickness
  - lower wall: y=0 outside the hump; y(x) = Glauert-Goldschmied profile
    on x in [0, 1] with apex y/c ~ 0.128
  - top wall (y=0.91): symmetry / Euler slip
  - inlet at x=-2.14 (upstream reference station of experiment)
  - outlet at x=4.0

Mesh: 3 blocks in x (upstream flat / hump / downstream flat) with
strong wall clustering (y+ ~ 30 with wall functions on a wall-resolved
nutUSpalding setup).

Bump profile coordinates: NASA TMR digitised approximation (close to
xy_v2.dat); apex y/c=0.128 around x/c=0.27, peak suction at x/c~0.48,
TE at (1, 0). Used as polyLine edge between block vertices.

Run from inside `case/`:  python3 ../gen_blockmesh.py > system/blockMeshDict
"""
from __future__ import annotations

import sys

# --- hump coordinates (x, y) on x in (0, 1) ---
# Approximate Glauert-Goldschmied published in NASA TMR; close enough
# to the digitised xy_v2.dat that peak suction at x/c~0.48 reproduces.
HUMP_PTS = [
    (0.025, 0.00400),
    (0.050, 0.01450),
    (0.075, 0.02850),
    (0.100, 0.04320),
    (0.125, 0.05950),
    (0.150, 0.07600),
    (0.175, 0.09200),
    (0.200, 0.10500),
    (0.225, 0.11500),
    (0.250, 0.12100),
    (0.275, 0.12300),
    (0.300, 0.12340),
    (0.325, 0.12330),
    (0.350, 0.12280),
    (0.375, 0.12230),
    (0.400, 0.12160),
    (0.425, 0.12080),
    (0.450, 0.11960),
    (0.475, 0.11790),
    (0.500, 0.11530),
    (0.525, 0.11320),
    (0.550, 0.11050),
    (0.575, 0.10750),
    (0.600, 0.10370),
    (0.625, 0.09920),
    (0.650, 0.09420),
    (0.675, 0.08810),
    (0.700, 0.08090),
    (0.725, 0.07300),
    (0.750, 0.06410),
    (0.775, 0.05450),
    (0.800, 0.04380),
    (0.825, 0.03250),
    (0.850, 0.02030),
    (0.875, 0.01000),
    (0.900, 0.00400),
    (0.925, 0.00200),
    (0.950, 0.00150),
    (0.975, 0.00100),
]

# --- vertices ----------------------------------------------------------------
# x-stations: -2.14 (inlet), 0 (LE), 1.0 (TE), 4.0 (outlet)
# y-stations: 0 (floor), 0.91 (ceiling)
# z: 0 (front), 1 (back)
xs = [-2.14, 0.0, 1.0, 4.0]
ys = [0.0, 0.91]
zs = [0.0, 1.0]

vertices = []
for z in zs:
    for y in ys:
        for x in xs:
            vertices.append((x, y, z))


def V(ix, iy, iz):
    return iz * 8 + iy * 4 + ix


nx1, nx2, nx3 = 100, 220, 160     # cells in x for the 3 blocks
ny = 110                           # cells in y
nz = 1
y_grading = 5000                   # strong clustering toward floor

out = []
out.append("/*--------------------------------*- C++ -*----------------------------------*/")
out.append("FoamFile")
out.append("{")
out.append("    version     2.0;")
out.append("    format      ascii;")
out.append("    class       dictionary;")
out.append("    object      blockMeshDict;")
out.append("}")
out.append("// Generated by gen_blockmesh.py - do not hand-edit; regenerate instead.")
out.append("")
out.append("scale   1;")
out.append("")
out.append("vertices")
out.append("(")
for i, (x, y, z) in enumerate(vertices):
    out.append(f"    ({x:>10.6f} {y:>10.6f} {z:>6.2f})    // {i}")
out.append(");")
out.append("")
out.append("blocks")
out.append("(")
out.append(f"    hex ({V(0,0,0)} {V(1,0,0)} {V(1,1,0)} {V(0,1,0)} {V(0,0,1)} {V(1,0,1)} {V(1,1,1)} {V(0,1,1)})  ({nx1} {ny} {nz}) simpleGrading (0.1 {y_grading} 1)")
out.append(f"    hex ({V(1,0,0)} {V(2,0,0)} {V(2,1,0)} {V(1,1,0)} {V(1,0,1)} {V(2,0,1)} {V(2,1,1)} {V(1,1,1)})  ({nx2} {ny} {nz}) simpleGrading (1 {y_grading} 1)")
out.append(f"    hex ({V(2,0,0)} {V(3,0,0)} {V(3,1,0)} {V(2,1,0)} {V(2,0,1)} {V(3,0,1)} {V(3,1,1)} {V(2,1,1)})  ({nx3} {ny} {nz}) simpleGrading (10 {y_grading} 1)")
out.append(");")
out.append("")
out.append("edges")
out.append("(")
# polyLine on z=0 plane: between V(1,0,0) -> V(2,0,0)
out.append(f"    polyLine {V(1,0,0)} {V(2,0,0)}")
out.append("    (")
for x, y in HUMP_PTS:
    out.append(f"        ({x:.6f} {y:.6f} 0.0)")
out.append("    )")
# polyLine on z=1 plane: between V(1,0,1) -> V(2,0,1)
out.append(f"    polyLine {V(1,0,1)} {V(2,0,1)}")
out.append("    (")
for x, y in HUMP_PTS:
    out.append(f"        ({x:.6f} {y:.6f} 1.0)")
out.append("    )")
out.append(");")
out.append("")
out.append("boundary")
out.append("(")
out.append("    inlet")
out.append("    {")
out.append("        type patch;")
out.append(f"        faces (({V(0,0,0)} {V(0,0,1)} {V(0,1,1)} {V(0,1,0)}));")
out.append("    }")
out.append("    outlet")
out.append("    {")
out.append("        type patch;")
out.append(f"        faces (({V(3,0,0)} {V(3,1,0)} {V(3,1,1)} {V(3,0,1)}));")
out.append("    }")
# Lower wall split: upstream / hump / downstream so the verifier can
# extract Cf along the hump separately. Agents see them as a wall group
# via the wildcard "wall_.*".
out.append("    wall_up")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(0,0,0)} {V(1,0,0)} {V(1,0,1)} {V(0,0,1)}));")
out.append("    }")
out.append("    wall_hump")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(1,0,0)} {V(2,0,0)} {V(2,0,1)} {V(1,0,1)}));")
out.append("    }")
out.append("    wall_down")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(2,0,0)} {V(3,0,0)} {V(3,0,1)} {V(2,0,1)}));")
out.append("    }")
out.append("    top")
out.append("    {")
out.append("        type symmetry;")
out.append("        faces")
out.append("        (")
out.append(f"            ({V(0,1,0)} {V(0,1,1)} {V(1,1,1)} {V(1,1,0)})")
out.append(f"            ({V(1,1,0)} {V(1,1,1)} {V(2,1,1)} {V(2,1,0)})")
out.append(f"            ({V(2,1,0)} {V(2,1,1)} {V(3,1,1)} {V(3,1,0)})")
out.append("        );")
out.append("    }")
out.append("    frontAndBack")
out.append("    {")
out.append("        type empty;")
out.append("        faces")
out.append("        (")
out.append(f"            ({V(0,0,0)} {V(0,1,0)} {V(1,1,0)} {V(1,0,0)})")
out.append(f"            ({V(1,0,0)} {V(1,1,0)} {V(2,1,0)} {V(2,0,0)})")
out.append(f"            ({V(2,0,0)} {V(2,1,0)} {V(3,1,0)} {V(3,0,0)})")
out.append(f"            ({V(0,0,1)} {V(1,0,1)} {V(1,1,1)} {V(0,1,1)})")
out.append(f"            ({V(1,0,1)} {V(2,0,1)} {V(2,1,1)} {V(1,1,1)})")
out.append(f"            ({V(2,0,1)} {V(3,0,1)} {V(3,1,1)} {V(2,1,1)})")
out.append("        );")
out.append("    }")
out.append(");")
out.append("")
out.append("mergePatchPairs ();")

sys.stdout.write("\n".join(out) + "\n")
