#!/usr/bin/env python3
"""Generate blockMeshDict for the NASA TMR 2D bump-in-channel oracle.

Geometry:
  - channel x in [-25, 26.5], y in [0, 5], unit z-thickness
  - lower wall: y=0 outside the bump; y(x) = 0.05 * sin^4(pi*x/1.5) for x in [0, 1.5]
  - upper wall (y=5): symmetry / Euler slip
  - inlet at x=-25, outlet at x=26.5

Mesh: 3 blocks in x to cluster cells around the bump:
  block 1: x in [-25, 0]   (80 cells, graded compressing toward x=0)
  block 2: x in [0, 1.5]   (140 cells, uniform)
  block 3: x in [1.5, 26.5] (100 cells, graded compressing toward x=1.5)
Each block: 120 cells in y with simpleGrading 50000 (first cell ~9e-6, y+~1
at Re=3e6 with U=1).

Run from inside `case/`:  python3 ../gen_blockmesh.py > system/blockMeshDict
"""
from __future__ import annotations

import math
import sys

# --- bump shape sampling ---------------------------------------------------
N_BUMP_POINTS = 30  # number of internal polyLine points on the bump

def y_wall(x: float) -> float:
    if x <= 0.0 or x >= 1.5:
        return 0.0
    return 0.05 * math.sin(math.pi * x / 1.5) ** 4

bump_pts = []
# uniform sample in x in (0, 1.5), excluding endpoints which are vertices
for k in range(1, N_BUMP_POINTS + 1):
    x = 1.5 * k / (N_BUMP_POINTS + 1)
    bump_pts.append((x, y_wall(x)))

# --- vertices ---------------------------------------------------------------
# z = 0 plane (vertices 0..7)
# z = 1 plane (vertices 8..15)
xs = [-25.0, 0.0, 1.5, 26.5]
ys = [0.0, 5.0]
zs = [0.0, 1.0]

vertices = []
for z in zs:
    for y in ys:
        for x in xs:
            vertices.append((x, y, z))
# Index map: vertex(i_x, i_y, i_z) = i_z*8 + i_y*4 + i_x
def V(ix, iy, iz):
    return iz * 8 + iy * 4 + ix

# --- output -----------------------------------------------------------------
out = []
out.append("/*--------------------------------*- C++ -*----------------------------------*/")
out.append("FoamFile")
out.append("{")
out.append("    version     2.0;")
out.append("    format      ascii;")
out.append("    class       dictionary;")
out.append("    object      blockMeshDict;")
out.append("}")
out.append("// Generated by gen_blockmesh.py - do not hand-edit; regenerate instead.")
out.append("")
out.append("scale   1;")
out.append("")
out.append("vertices")
out.append("(")
for i, (x, y, z) in enumerate(vertices):
    out.append(f"    ({x:>8} {y:>8} {z:>8})    // {i}")
out.append(");")
out.append("")
out.append("blocks")
out.append("(")
# Block 1: upstream  (x[-25,0])  - vertices 0,1,5,4 + 8,9,13,12
# Block 2: bump      (x[0,1.5])  - vertices 1,2,6,5 + 9,10,14,13
# Block 3: downstream(x[1.5,26.5]) - vertices 2,3,7,6 + 10,11,15,14
# Cell counts:
nx1, nx2, nx3 = 100, 160, 120
ny = 130
nz = 1
y_grading = 50000
out.append(f"    hex ({V(0,0,0)} {V(1,0,0)} {V(1,1,0)} {V(0,1,0)} {V(0,0,1)} {V(1,0,1)} {V(1,1,1)} {V(0,1,1)})  ({nx1} {ny} {nz}) simpleGrading (0.05 {y_grading} 1)")
out.append(f"    hex ({V(1,0,0)} {V(2,0,0)} {V(2,1,0)} {V(1,1,0)} {V(1,0,1)} {V(2,0,1)} {V(2,1,1)} {V(1,1,1)})  ({nx2} {ny} {nz}) simpleGrading (1 {y_grading} 1)")
out.append(f"    hex ({V(2,0,0)} {V(3,0,0)} {V(3,1,0)} {V(2,1,0)} {V(2,0,1)} {V(3,0,1)} {V(3,1,1)} {V(2,1,1)})  ({nx3} {ny} {nz}) simpleGrading (20 {y_grading} 1)")
out.append(");")
out.append("")
out.append("edges")
out.append("(")
# polyLine for the bump bottom edge on z=0 and z=1 planes
# z=0 bottom edge of bump block: vertex V(1,0,0) -> V(2,0,0)
out.append(f"    polyLine {V(1,0,0)} {V(2,0,0)}")
out.append("    (")
for x, y in bump_pts:
    out.append(f"        ({x:.6f} {y:.8f} 0)")
out.append("    )")
out.append(f"    polyLine {V(1,0,1)} {V(2,0,1)}")
out.append("    (")
for x, y in bump_pts:
    out.append(f"        ({x:.6f} {y:.8f} 1)")
out.append("    )")
out.append(");")
out.append("")
out.append("boundary")
out.append("(")
out.append("    inlet")
out.append("    {")
out.append("        type patch;")
out.append(f"        faces (({V(0,0,0)} {V(0,0,1)} {V(0,1,1)} {V(0,1,0)}));")
out.append("    }")
out.append("    outlet")
out.append("    {")
out.append("        type patch;")
out.append(f"        faces (({V(3,0,0)} {V(3,1,0)} {V(3,1,1)} {V(3,0,1)}));")
out.append("    }")
# Lower wall split into 3 patches so forceCoeffs can integrate the
# pressure + viscous drag over the bump region only (x in [0, 1.5]) —
# matches the CFL3D reference convention. Agents see all 3 as a wall
# group via the wildcard "wall_.*" in their boundary-condition fields.
out.append("    wall_up")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(0,0,0)} {V(1,0,0)} {V(1,0,1)} {V(0,0,1)}));")
out.append("    }")
out.append("    wall_bump")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(1,0,0)} {V(2,0,0)} {V(2,0,1)} {V(1,0,1)}));")
out.append("    }")
out.append("    wall_down")
out.append("    {")
out.append("        type wall;")
out.append(f"        faces (({V(2,0,0)} {V(3,0,0)} {V(3,0,1)} {V(2,0,1)}));")
out.append("    }")
out.append("    top")
out.append("    {")
out.append("        type symmetry;")
out.append("        faces")
out.append("        (")
out.append(f"            ({V(0,1,0)} {V(0,1,1)} {V(1,1,1)} {V(1,1,0)})")
out.append(f"            ({V(1,1,0)} {V(1,1,1)} {V(2,1,1)} {V(2,1,0)})")
out.append(f"            ({V(2,1,0)} {V(2,1,1)} {V(3,1,1)} {V(3,1,0)})")
out.append("        );")
out.append("    }")
out.append("    frontAndBack")
out.append("    {")
out.append("        type empty;")
out.append("        faces")
out.append("        (")
# z=0 face of each block (front)
out.append(f"            ({V(0,0,0)} {V(0,1,0)} {V(1,1,0)} {V(1,0,0)})")
out.append(f"            ({V(1,0,0)} {V(1,1,0)} {V(2,1,0)} {V(2,0,0)})")
out.append(f"            ({V(2,0,0)} {V(2,1,0)} {V(3,1,0)} {V(3,0,0)})")
# z=1 face of each block (back)
out.append(f"            ({V(0,0,1)} {V(1,0,1)} {V(1,1,1)} {V(0,1,1)})")
out.append(f"            ({V(1,0,1)} {V(2,0,1)} {V(2,1,1)} {V(1,1,1)})")
out.append(f"            ({V(2,0,1)} {V(3,0,1)} {V(3,1,1)} {V(2,1,1)})")
out.append("        );")
out.append("    }")
out.append(");")
out.append("")
out.append("mergePatchPairs ();")

sys.stdout.write("\n".join(out) + "\n")
